### ISSUE TITLE
Issue on page /workflow.html

### ISSUE THREAD

**Issue by dktanwar** [kashyapchhatbar/eme_selex#1]
I am trying to reproduce the notebook.

I guess, I can download the data from https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-9236

But, I would like to have `"data/metadata.tsv"` file. I.would be great if you could please provide this file, so that I can run the notebook with minimal efforts.

Thank you very much.

**Comment by dktanwar** [comment]
I found this file, but still the notebook is not reproducible.

**Comment by kashyapchhatbar** [comment]
Hi @dktanwar,

Thanks for getting in touch. Apologies for not replying sooner. Can you send some more information about the error? 

Best,
Kashyap

**Comment by kashyapchhatbar** [comment]
I have added two minor fixes which were related to `pandas`. These changes are necessary since `pandas` are handling some defaults in a different way.

Can you let me know if following these steps help?

### Clone the repository 

```
git clone https://github.com/kashyapchhatbar/eme_selex.git
```

### Navigate in the `docs` directory

```
cd eme_selex/docs
```

### Make sure you have all the python packages 

Follow this link https://eme-selex.readthedocs.io/en/latest/workflow.html#before-you-begin for more information

When you run the Notebook.ipynb in Jupyter, the notebook shouldn't throw any error. Please let me know if it doesn't work.

Many thanks,
Kashyap
